# https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-react-and-next

name: CI

on:
  push:
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.11.0
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.0'

      - name: Install Packages
        run: |
          corepack enable
          yarn install

      - name: Check Lint and Format
        run: |
          yarn ci
