# https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-react-and-next

name: CI

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  CI:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 22.12.0
        uses: actions/setup-node@v4
        with:
          node-version: '22.12.0'

      - name: Monorepo install
        uses: ./.github/actions/yarn-nm-install
        with:
          cwd: '.'
          enable-corepack: true
          cache-node-modules: true
          cache-install-state: true

      - name: Check Lint and Format
        run: |
          yarn ci
