name: Build & Deploy Triplate Delete User Form

on:
  push:
    branches:
      - main
    paths:
      - triplate-delete-user-form/**
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js 20.11.0
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.0'

      - name: Install Packages
        run: |
          corepack enable
          yarn workspaces focus triplate-delete-user-form

      - name: Create .clasprc.json
        run: |
          echo "${{ secrets.TRIPLATE_DEV_BASE64 }}" | base64 --decode > ~/.clasprc.json

      - name: Create .clasp.json
        run: |
          cat > ./triplate-delete-user-form/.clasp.json <<EOF
          {
            "scriptId": "${{ secrets.TRIPLATE_DELETE_USER_FORM_SCRIPT_ID }}",
            "rootDir": "./dist"
          }
          EOF

      - name: Build & Deploy
        run: |
          yarn workspace triplate-delete-user-form push
