name: Build & Deploy Sync Calendar

on:
  push:
    branches:
      - main
    paths:
      - packages/sync-calendar/**
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js 20.11.0
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.0'

      - name: Install Packages
        run: |
          corepack enable
          yarn workspaces focus sync-calendar

      - name: Create .clasprc.json
        run: |
          echo "${{ secrets.CLASP_RC_BASE64 }}" | base64 --decode > ~/.clasprc.json

      - name: Create .clasp.json
        run: |
          cat > ./packages/sync-calendar/.clasp.json <<EOF
          {
            "scriptId": "${{ secrets.SYNC_CALENDAR_SCRIPT_ID }}",
            "rootDir": "./dist"
          }
          EOF

      - name: Build & Deploy
        run: |
          yarn workspace sync-calendar push
